# -*- coding: utf-8 -*-
"""MidtermMLProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zi-YIffi4cupPoycuBafXI0wj_PRKaYL
"""

import pandas as pd

df = pd.read_csv("/content/Crime_Data_from_2020_to_Present.csv")

print("Dataset Shape(Rows, Columns):", df.shape)
print("\nColumns Names:", df.columns)

print("\nInfo:")
print(df.info())

print("\nSummary (Numeric):")
print(df.describe())

print("\nMissing Values:")
print(df.isnull().sum())

# Fill Vict Sex
df['Vict Sex'] = df['Vict Sex'].fillna('Unknown')

# Fill Vict Descent
df['Vict Descent'] = df['Vict Descent'].fillna('Unknown')

# Fill Premis Desc
df['Premis Desc'] = df['Premis Desc'].fillna('Unknown')

# Fill Weapon Desc
df['Weapon Desc'] = df['Weapon Desc'].fillna('Unknown')

# Fill Mocodes
df['Mocodes'] = df['Mocodes'].fillna('None')

# Fill Crm Cd 1
df['Crm Cd 1'] = df['Crm Cd 1'].fillna(0)

# Fill Crm Cd 2
df['Crm Cd 2'] = df['Crm Cd 2'].fillna(0)

# Fill Crm Cd 3
df['Crm Cd 3'] = df['Crm Cd 3'].fillna(0)

# Fill Crm Cd 4
df['Crm Cd 4'] = df['Crm Cd 4'].fillna(0)

# Fill Premis Cd (if needed)
df['Premis Cd'] = df['Premis Cd'].fillna(0)

# Fill Weapon Used Cd (if needed)
df['Weapon Used Cd'] = df['Weapon Used Cd'].fillna(0)

# Fill Cross Street (optional, you can also leave it as NaN)
df['Cross Street'] = df['Cross Street'].fillna('Unknown')

print("\nMissing Values:")
print(df.isnull().sum())

print(df.head(5))

# a. Top 5 most common crime types
top_crimes = df['Crm Cd Desc'].value_counts().head(5)
print("\nTop 5 Most Common Crimes:")
print(top_crimes)

#Crime count by area
crime_by_area = df['AREA NAME'].value_counts()
print("\nCrime Count by Area:")
print(crime_by_area)

df['DATE OCC'] = pd.to_datetime(df['DATE OCC'], errors='coerce')

# Now extract the year
df['Year'] = df['DATE OCC'].dt.year

# Continue with crime count by year
crime_by_year = df['Year'].value_counts().sort_index()
print("\nCrime Count by Year:")
print(crime_by_year)

# e. Most common weapons used
weapon_counts = df['Weapon Desc'].value_counts().head(5)
print("\nTop 5 Most Common Weapons Used:")
print(weapon_counts)

# Area + crime type cross analysis (top 3 combinations)
area_crime_combo = df.groupby(['AREA NAME', 'Crm Cd Desc']).size().sort_values(ascending=False).head(5)
print("\nTop 3 Area + Crime Type Combinations:")
print(area_crime_combo)

#Most affected victim age groups (bucketed)
df['Vict Age'] = pd.to_numeric(df['Vict Age'], errors='coerce')
df['Age Group'] = pd.cut(df['Vict Age'], bins=[0, 18, 30, 50, 70, 120],
                         labels=['0-18', '19-30', '31-50', '51-70', '71+'])
age_group_counts = df.groupby('Age Group').size().sort_values(ascending=False)
print("\nVictim Age Group Counts:")
print(age_group_counts)

# First, make sure TIME OCC is numeric (it’s often a string or int like 1345 → 13:45)
df['Hour'] = pd.to_numeric(df['TIME OCC'], errors='coerce') // 100  # Convert to hour only (military time)

# Create time-of-day categories
df['Time of Day'] = pd.cut(df['Hour'], bins=[0, 6, 12, 18, 24],
                           labels=['Night (0-6)', 'Morning (6-12)', 'Afternoon (12-18)', 'Evening (18-24)'],
                           right=False)

# Group by time of day
crimes_by_time = df.groupby('Time of Day').size().sort_values(ascending=False)
print("\nCrimes by Time of Day:")
print(crimes_by_time)